//图书优惠规则
package com.jsh.droolsdemo
import com.jsh.droolsdemo.entity.Order
import com.jsh.droolsdemo.entity.Cat
import java.util.List
import com.jsh.droolsdemo.util.MessageList

//添加方法
function void setString(String s) {
    MessageList.add(s);
}

//规则一：所购图书总价在100元以下的没有优惠
//rule "book_discount_1"
//
//    when
//        $order:Order(originalPrice < 100)
//    then
//        $order.setRealPrice($order.getOriginalPrice() - 10);
//        System.out.println("成功匹配到规则1：所购图书总价在300元以上的优惠100元");
//end
//
////规则四：所购图书总价在300元以上的优惠100元
//rule "book_discount_4"
////activation-group "001"
////agenda-group "001"
////ruleflow-group "001"
////salience "2"
//    when
//        $order:Order(originalPrice < 90)
//    then
//        $order.setRealPrice($order.getOriginalPrice() - 20);
//        System.out.println("成功匹配到规则2：所购图书总价在300元以上的优惠100元");
//end

////规则二：所购图书总价在100到200元的优惠20元
//rule "book_discount_2"
//activation-group "002"
//    when
//        $order:Order(originalPrice < 200)
//    then
//        $order.setRealPrice($order.getOriginalPrice() - 20);
//        System.out.println("成功匹配到规则二：所购图书总价在100到200元的优惠20元");
//end
//
////规则三：所购图书总价在200到300元的优惠50元
//rule "book_discount_3"
//    when
//        $order:Order(originalPrice <= 300 && originalPrice >= 200)
//    then
//        $order.setRealPrice($order.getOriginalPrice() - 50);
//        System.out.println("成功匹配到规则三：所购图书总价在200到300元的优惠50元");
//end



////规则五：测试不同对象
//rule "book_discount_5"
//    when
//        $order:Order(originalPrice < 100) and $cat:Cat(sex == 0)
//    then
//        System.out.println("公");
//end